# Common properties shared across all environments

# Listener configuration
https:
  host: "0.0.0.0"
  port: "8082"
  path: "/api/*"
  timeout: "30000"
  
# Reconnection strategy
reconnect:
  frequency: "3000"
  count: "3"

# Retry configuration
retry:
  delayMillisecs: "3000"
  numRetries: "3"